-- TD Jogos — schema
-- Rodar no Supabase SQL Editor no projeto novo.

create extension if not exists unaccent;

-- =====================================================
-- 1. Tabelas
-- =====================================================

create table if not exists groups (
  id smallint primary key,
  nome text not null,
  cor text not null
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome_exibicao text not null,
  email text unique,
  group_id smallint references groups(id),
  role text not null default 'user' check (role in ('user','admin','superadmin')),
  ativo boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists pending_claims (
  -- profiles "de espera" seedados antes do usuário logar pela primeira vez
  id smallint generated by default as identity primary key,
  nome_exibicao text not null,
  email text,
  group_id smallint references groups(id),
  role text not null default 'user',
  claimed_by uuid references auth.users(id),
  claimed_at timestamptz
);

create table if not exists posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  categoria text not null check (categoria in ('energia','movimento','mental')),
  data_registro date not null default current_date,
  quantidade_frutas smallint check (quantidade_frutas between 1 and 2),
  minutos smallint check (minutos > 0),
  foto_url text not null,
  pontos smallint not null default 0,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references profiles(id),
  reviewed_at timestamptz,
  motivo_reprovacao text,
  foto_liberada boolean not null default false,
  created_at timestamptz default now(),
  constraint chk_energia check (
    categoria != 'energia' or (quantidade_frutas is not null and minutos is null)
  ),
  constraint chk_mov_mental check (
    categoria = 'energia' or (minutos is not null and quantidade_frutas is null)
  )
);

create index if not exists idx_posts_user_data on posts (user_id, data_registro);
create index if not exists idx_posts_status on posts (status);

create table if not exists email_exceptions (
  email text primary key,
  nome_exibicao text,
  observacao text,
  criado_por uuid references profiles(id),
  created_at timestamptz default now()
);

create table if not exists challenge_config (
  id smallint primary key default 1 check (id = 1),
  data_inicio date not null,
  data_fim date not null
);

insert into challenge_config (id, data_inicio, data_fim)
values (1, '2026-04-20', '2026-05-10')
on conflict (id) do nothing;

-- =====================================================
-- Função: email é permitido a logar?
-- =====================================================
create or replace function public.email_allowed(p_email text)
returns boolean
language sql
stable
as $$
  select
    lower(p_email) like '%@tributodevido.com.br'
    or exists (select 1 from email_exceptions where lower(email) = lower(p_email));
$$;

grant execute on function public.email_allowed(text) to anon, authenticated;

-- =====================================================
-- 2. Função de pontuação
-- =====================================================

create or replace function calcular_pontos(
  p_categoria text,
  p_minutos int,
  p_qtd int,
  p_data date
) returns smallint
language plpgsql
as $$
declare
  v_inicio date;
  v_fim date;
  v_semana int;
  v_meta_mov int;
  v_meta_men int;
begin
  v_inicio := (select data_inicio from challenge_config where id = 1);
  v_fim    := (select data_fim    from challenge_config where id = 1);

  -- Pre-desafio ou pos-desafio: zero pontos.
  if p_data < v_inicio or p_data > v_fim then
    return 0;
  end if;

  -- So dias uteis contam. Sabado (6) e domingo (0) nao pontuam.
  if extract(dow from p_data) in (0, 6) then
    return 0;
  end if;
  -- Feriados nacionais no periodo do desafio.
  if p_data in (date '2026-04-21', date '2026-05-01') then
    return 0;
  end if;

  if p_categoria = 'energia' then
    return coalesce(p_qtd, 0);
  end if;

  v_semana := ((p_data - v_inicio) / 7) + 1;

  v_meta_mov := case v_semana when 1 then 20 when 2 then 25 when 3 then 30 else 9999 end;
  v_meta_men := case v_semana when 1 then 3  when 2 then 4  when 3 then 5  else 9999 end;

  if p_categoria = 'movimento' and coalesce(p_minutos,0) >= v_meta_mov then
    return 3;
  end if;
  if p_categoria = 'mental' and coalesce(p_minutos,0) >= v_meta_men then
    return 2;
  end if;

  return 0;
end;
$$;

-- =====================================================
-- 3. Trigger de limite diário (antes do insert)
-- =====================================================

create or replace function enforce_daily_limits()
returns trigger
language plpgsql
as $$
declare
  v_soma int;
  v_ja_tem int;
begin
  if NEW.categoria = 'energia' then
    v_soma := coalesce((
      select sum(quantidade_frutas) from posts
      where user_id = NEW.user_id
        and data_registro = NEW.data_registro
        and categoria = 'energia'
        and status in ('pending','approved')
    ), 0);
    if v_soma + coalesce(NEW.quantidade_frutas,0) > 2 then
      raise exception 'Limite de 2 frutas por dia excedido.';
    end if;
  else
    v_ja_tem := (
      select count(*) from posts
      where user_id = NEW.user_id
        and data_registro = NEW.data_registro
        and categoria = NEW.categoria
        and status in ('pending','approved')
    );
    if v_ja_tem > 0 then
      raise exception 'Você já registrou % hoje.', NEW.categoria;
    end if;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_enforce_daily_limits on posts;
create trigger trg_enforce_daily_limits
  before insert on posts
  for each row execute function enforce_daily_limits();

-- =====================================================
-- 4. Trigger de recálculo de pontos ao aprovar
-- =====================================================

create or replace function recalc_pontos_on_approve()
returns trigger
language plpgsql
as $$
begin
  if NEW.status = 'approved' and (OLD.status is distinct from 'approved') then
    NEW.pontos := calcular_pontos(NEW.categoria, NEW.minutos, NEW.quantidade_frutas, NEW.data_registro);
  end if;
  if NEW.status <> 'approved' then
    NEW.pontos := 0;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_recalc_pontos on posts;
create trigger trg_recalc_pontos
  before update on posts
  for each row execute function recalc_pontos_on_approve();

-- =====================================================
-- 5. Função auxiliar para reivindicar profile no 1º login
-- =====================================================

create or replace function claim_pending_profile(p_nome text, p_email text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claim_id int;
  v_uid uuid := auth.uid();
  v_normalized text := lower(public.unaccent(coalesce(p_nome,'')));
  v_first_token text := split_part(v_normalized, ' ', 1);
begin
  if v_uid is null then
    raise exception 'sem sessao';
  end if;

  if exists (select 1 from profiles where id = v_uid) then
    return v_uid;
  end if;

  -- match 1: por email exato
  v_claim_id := (
    select id from pending_claims
    where claimed_by is null
      and email is not null
      and lower(email) = lower(p_email)
    limit 1
  );

  -- match 2: nome completo normalizado
  if v_claim_id is null then
    v_claim_id := (
      select id from pending_claims
      where claimed_by is null
        and lower(public.unaccent(nome_exibicao)) = v_normalized
      limit 1
    );
  end if;

  -- match 3: primeiro nome normalizado (Google retorna nome completo, seed tem nome parcial)
  if v_claim_id is null and length(v_first_token) >= 3 then
    v_claim_id := (
      select id from pending_claims
      where claimed_by is null
        and lower(split_part(public.unaccent(nome_exibicao), ' ', 1)) = v_first_token
      limit 1
    );
  end if;

  if v_claim_id is null then
    insert into profiles (id, nome_exibicao, email, role)
      values (v_uid, coalesce(p_nome, p_email), p_email, 'user');
    return v_uid;
  end if;

  insert into profiles (id, nome_exibicao, email, group_id, role)
    select v_uid, nome_exibicao, p_email, group_id, role
    from pending_claims
    where id = v_claim_id;

  update pending_claims
    set claimed_by = v_uid, claimed_at = now()
    where id = v_claim_id;

  return v_uid;
end;
$$;

