-- TD Jogos — schema
-- Rodar no Supabase SQL Editor no projeto novo.

-- =====================================================
-- 1. Tabelas
-- =====================================================

create table if not exists groups (
  id smallint primary key,
  nome text not null,
  cor text not null
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome_exibicao text not null,
  email text unique,
  group_id smallint references groups(id),
  role text not null default 'user' check (role in ('user','admin','superadmin')),
  ativo boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists pending_claims (
  -- profiles "de espera" seedados antes do usuário logar pela primeira vez
  id smallint generated by default as identity primary key,
  nome_exibicao text not null,
  email text,
  group_id smallint references groups(id),
  role text not null default 'user',
  claimed_by uuid references auth.users(id),
  claimed_at timestamptz
);

create table if not exists posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  categoria text not null check (categoria in ('energia','movimento','mental')),
  data_registro date not null default current_date,
  quantidade_frutas smallint check (quantidade_frutas between 1 and 2),
  minutos smallint check (minutos > 0),
  foto_url text not null,
  pontos smallint not null default 0,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references profiles(id),
  reviewed_at timestamptz,
  motivo_reprovacao text,
  created_at timestamptz default now(),
  constraint chk_energia check (
    categoria != 'energia' or (quantidade_frutas is not null and minutos is null)
  ),
  constraint chk_mov_mental check (
    categoria = 'energia' or (minutos is not null and quantidade_frutas is null)
  )
);

create index if not exists idx_posts_user_data on posts (user_id, data_registro);
create index if not exists idx_posts_status on posts (status);

create table if not exists challenge_config (
  id smallint primary key default 1 check (id = 1),
  data_inicio date not null,
  data_fim date not null
);

insert into challenge_config (id, data_inicio, data_fim)
values (1, '2026-04-20', '2026-05-10')
on conflict (id) do nothing;

-- =====================================================
-- 2. Função de pontuação
-- =====================================================

create or replace function calcular_pontos(
  p_categoria text,
  p_minutos int,
  p_qtd int,
  p_data date
) returns smallint
language plpgsql
as $$
declare
  semana int;
  meta_mov int;
  meta_men int;
begin
  select (p_data - data_inicio)/7 + 1
    into semana
    from challenge_config where id = 1;

  if p_categoria = 'energia' then
    return coalesce(p_qtd, 0);
  end if;

  meta_mov := case semana when 1 then 20 when 2 then 25 when 3 then 30 else 9999 end;
  meta_men := case semana when 1 then 3  when 2 then 4  when 3 then 5  else 9999 end;

  if p_categoria = 'movimento' and coalesce(p_minutos,0) >= meta_mov then
    return 3;
  end if;
  if p_categoria = 'mental' and coalesce(p_minutos,0) >= meta_men then
    return 2;
  end if;

  return 0;
end;
$$;

-- =====================================================
-- 3. Trigger de limite diário (antes do insert)
-- =====================================================

create or replace function enforce_daily_limits()
returns trigger
language plpgsql
as $$
declare
  soma_frutas int;
  ja_tem int;
begin
  if NEW.categoria = 'energia' then
    select coalesce(sum(quantidade_frutas),0)
      into soma_frutas
      from posts
      where user_id = NEW.user_id
        and data_registro = NEW.data_registro
        and categoria = 'energia'
        and status in ('pending','approved');
    if soma_frutas + coalesce(NEW.quantidade_frutas,0) > 2 then
      raise exception 'Limite de 2 frutas por dia excedido.';
    end if;
  else
    select count(*)
      into ja_tem
      from posts
      where user_id = NEW.user_id
        and data_registro = NEW.data_registro
        and categoria = NEW.categoria
        and status in ('pending','approved');
    if ja_tem > 0 then
      raise exception 'Você já registrou % hoje.', NEW.categoria;
    end if;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_enforce_daily_limits on posts;
create trigger trg_enforce_daily_limits
  before insert on posts
  for each row execute function enforce_daily_limits();

-- =====================================================
-- 4. Trigger de recálculo de pontos ao aprovar
-- =====================================================

create or replace function recalc_pontos_on_approve()
returns trigger
language plpgsql
as $$
begin
  if NEW.status = 'approved' and (OLD.status is distinct from 'approved') then
    NEW.pontos := calcular_pontos(NEW.categoria, NEW.minutos, NEW.quantidade_frutas, NEW.data_registro);
  end if;
  if NEW.status <> 'approved' then
    NEW.pontos := 0;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_recalc_pontos on posts;
create trigger trg_recalc_pontos
  before update on posts
  for each row execute function recalc_pontos_on_approve();

-- =====================================================
-- 5. Função auxiliar para reivindicar profile no 1º login
-- =====================================================

create or replace function claim_pending_profile(p_nome text, p_email text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claim pending_claims%rowtype;
  v_uid uuid := auth.uid();
  v_normalized text := lower(unaccent(coalesce(p_nome,'')));
begin
  if v_uid is null then
    raise exception 'sem sessao';
  end if;

  -- já tem profile
  if exists (select 1 from profiles where id = v_uid) then
    return v_uid;
  end if;

  -- tenta match por email
  select * into v_claim from pending_claims
    where claimed_by is null
      and email is not null
      and lower(email) = lower(p_email)
    limit 1;

  -- fallback por nome normalizado
  if v_claim.id is null then
    select * into v_claim from pending_claims
      where claimed_by is null
        and lower(unaccent(nome_exibicao)) = v_normalized
      limit 1;
  end if;

  if v_claim.id is null then
    -- sem match: cria profile mínimo desvinculado de grupo; admin vai vincular depois
    insert into profiles (id, nome_exibicao, email, role)
      values (v_uid, coalesce(p_nome, p_email), p_email, 'user');
    return v_uid;
  end if;

  insert into profiles (id, nome_exibicao, email, group_id, role)
    values (v_uid, v_claim.nome_exibicao, p_email, v_claim.group_id, v_claim.role);

  update pending_claims
    set claimed_by = v_uid, claimed_at = now()
    where id = v_claim.id;

  return v_uid;
end;
$$;

-- unaccent extension (ignorar erro se não tiver permissão)
create extension if not exists unaccent;
